"""add normalized data

Revision ID: 345ef771ea70
Revises: c08171bf976d
Create Date: 2026-01-14 15:10:54.080258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '345ef771ea70'
down_revision: Union[str, Sequence[str], None] = 'c08171bf976d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normalized_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('guest_temp_id', sa.String(length=64), nullable=True),
    sa.Column('average_guest_data_vector', Vector(512), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Integer(), nullable=False),
    sa.Column('movement_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('average_match_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_guest_movement_ts', 'normalized_data', ['guest_temp_id', 'movement_ts'], unique=False)
    op.create_index('ix_norm_member_movement_ts', 'normalized_data', ['member_id', 'movement_ts'], unique=False)
    op.create_index(op.f('ix_normalized_data_id'), 'normalized_data', ['id'], unique=False)
    op.drop_table('raw_data_sample')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data_sample',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('data_ts', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guest_temp_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('guest_data_vector', Vector(512), autoincrement=False, nullable=True),
    sa.Column('match_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_data_sample_pkey'))
    )
    op.drop_index(op.f('ix_normalized_data_id'), table_name='normalized_data')
    op.drop_index('ix_norm_member_movement_ts', table_name='normalized_data')
    op.drop_index('ix_norm_guest_movement_ts', table_name='normalized_data')
    op.drop_table('normalized_data')
    # ### end Alembic commands ###
