"""Site Locations :  Removed parent_site_location_id , Added is_protected

Revision ID: 3e8de82790f3
Revises: 4e2fad2ecbc8
Create Date: 2026-02-06 18:38:45.970949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e8de82790f3'
down_revision: Union[str, Sequence[str], None] = '4e2fad2ecbc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # add new column safely
    op.add_column(
        'site_locations',
        sa.Column('is_protected', sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.alter_column('site_locations', 'is_protected', server_default=None)

    # drop FK first
    op.drop_constraint(
        'site_locations_parent_site_location_id_fkey',
        'site_locations',
        type_='foreignkey'
    )

    # then drop the column
    op.drop_column('site_locations', 'parent_site_location_id')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_locations', sa.Column('parent_site_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('site_locations_parent_site_location_id_fkey'), 'site_locations', 'site_locations', ['parent_site_location_id'], ['id'])
    op.drop_column('site_locations', 'is_protected')
    op.add_column('cameras', sa.Column('location_type', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
