"""hierarchy name unique

Revision ID: 4e2fad2ecbc8
Revises: 345ef771ea70
Create Date: 2026-02-06 13:19:08.209319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2fad2ecbc8'
down_revision: Union[str, Sequence[str], None] = '345ef771ea70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_site_hierarchy_name', 'site_hierarchies', ['name'])
    op.create_unique_constraint(None, 'site_hierarchies', ['name'])
    op.drop_constraint(op.f('site_locations_parent_site_location_id_fkey'), 'site_locations', type_='foreignkey')
    op.drop_constraint(op.f('site_locations_site_hierarchy_id_fkey'), 'site_locations', type_='foreignkey')
    op.create_foreign_key(None, 'site_locations', 'site_locations', ['parent_site_location_id'], ['id'])
    op.create_foreign_key(None, 'site_locations', 'site_hierarchies', ['site_hierarchy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_locations', type_='foreignkey')
    op.drop_constraint(None, 'site_locations', type_='foreignkey')
    op.create_foreign_key(op.f('site_locations_site_hierarchy_id_fkey'), 'site_locations', 'site_hierarchies', ['site_hierarchy_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('site_locations_parent_site_location_id_fkey'), 'site_locations', 'site_locations', ['parent_site_location_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'site_hierarchies', type_='unique')
    op.drop_constraint('uq_site_hierarchy_name', 'site_hierarchies', type_='unique')
    # ### end Alembic commands ###
