"""normalized table changes update movement_ts to entry_ts and add exit_ts

Revision ID: ab7e309edb6c
Revises: ea1107c8da95
Create Date: 2026-03-12 15:10:02.651062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab7e309edb6c'
down_revision: Union[str, Sequence[str], None] = 'ea1107c8da95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data_registry')
    op.add_column('normalized_data', sa.Column('entry_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('normalized_data', sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_norm_guest_movement_ts'), table_name='normalized_data')
    op.drop_index(op.f('ix_norm_member_movement_ts'), table_name='normalized_data')
    op.create_index('ix_norm_guest_entry_ts', 'normalized_data', ['guest_temp_id', 'entry_ts'], unique=False)
    op.create_index('ix_norm_member_entry_ts', 'normalized_data', ['member_id', 'entry_ts'], unique=False)
    op.drop_column('normalized_data', 'movement_ts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_data', sa.Column('movement_ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index('ix_norm_member_entry_ts', table_name='normalized_data')
    op.drop_index('ix_norm_guest_entry_ts', table_name='normalized_data')
    op.create_index(op.f('ix_norm_member_movement_ts'), 'normalized_data', ['member_id', 'movement_ts'], unique=False)
    op.create_index(op.f('ix_norm_guest_movement_ts'), 'normalized_data', ['guest_temp_id', 'movement_ts'], unique=False)
    op.drop_column('normalized_data', 'exit_ts')
    op.drop_column('normalized_data', 'entry_ts')
    op.create_table('raw_data_registry',
    sa.Column('table_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('normalized', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('table_name', name=op.f('raw_data_registry_pkey'))
    )
    # ### end Alembic commands ###
