"""initial schema

Revision ID: c08171bf976d
Revises: 
Create Date: 2026-01-14 13:06:33.094632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c08171bf976d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_access_group_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_access_group_id'], ['access_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_groups_id'), 'access_groups', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('site_hierarchies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('parent_site_hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_site_hierarchy_id'], ['site_hierarchies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_hierarchies_id'), 'site_hierarchies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('activity_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_target', 'activity_logs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_number', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_number')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('site_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('site_hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('parent_site_location_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['parent_site_location_id'], ['site_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_hierarchy_id'], ['site_hierarchies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_locations_id'), 'site_locations', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=16), nullable=False),
    sa.Column('site_location_id', sa.Integer(), nullable=False),
    sa.Column('location_type', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['site_location_id'], ['site_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('member_access',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'access_group_id')
    )
    op.create_table('site_location_access',
    sa.Column('site_location_id', sa.Integer(), nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_location_id'], ['site_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_location_id', 'access_group_id')
    )
    op.create_table('member_embeddings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('body_embedding', Vector(512), nullable=True),
    sa.Column('face_embedding', Vector(512), nullable=True),
    sa.Column('back_body_embedding', Vector(512), nullable=True),
    sa.Column('body_embeddings_raw', sa.LargeBinary(), nullable=True),
    sa.Column('face_embeddings_raw', sa.LargeBinary(), nullable=True),
    sa.Column('back_body_embeddings_raw', sa.LargeBinary(), nullable=True),
    sa.Column('last_embedding_update_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_embedding_member_camera', 'member_embeddings', ['member_id', 'camera_id'], unique=False)
    op.create_index(op.f('ix_member_embeddings_id'), 'member_embeddings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('guest_temp_id', sa.String(length=64), nullable=True),
    sa.Column('average_guest_data_vector', Vector(512), nullable=True),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_camera_created', 'notifications', ['camera_id', 'created_ts'], unique=False)
    op.create_index('ix_notification_member_created', 'notifications', ['member_id', 'created_ts'], unique=False)
    op.create_index('ix_notification_type_status', 'notifications', ['type', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index('ix_notification_type_status', table_name='notifications')
    op.drop_index('ix_notification_member_created', table_name='notifications')
    op.drop_index('ix_notification_camera_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_member_embeddings_id'), table_name='member_embeddings')
    op.drop_index('ix_member_embedding_member_camera', table_name='member_embeddings')
    op.drop_table('member_embeddings')
    op.drop_table('site_location_access')
    op.drop_table('member_access')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_site_locations_id'), table_name='site_locations')
    op.drop_table('site_locations')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index('ix_activity_log_target', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_hierarchies_id'), table_name='site_hierarchies')
    op.drop_table('site_hierarchies')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_access_groups_id'), table_name='access_groups')
    op.drop_table('access_groups')
    # ### end Alembic commands ###
