"""Removed name from site locations

Revision ID: fbb068457b1e
Revises: 3e8de82790f3
Create Date: 2026-02-09 15:10:57.774936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb068457b1e'
down_revision: Union[str, Sequence[str], None] = '3e8de82790f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'location_type')
    op.drop_column('site_locations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_locations', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('cameras', sa.Column('location_type', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
